
name: onboarding_funnel_analysis   #project name
version: "1.0"
profile: ga4_funnel   #must match profile name in profiles.yml
config-version: 2

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"          # compiled SQL + artifacts
clean-targets: ["target", "dbt_packages"]